server_address: 0.0.0.0:5500 # SERVER_ADDRESS
reg_token_length: 32
jwt:
  algorithm: RS256
  issuer: idp.kallabs.by
  audience: 
    - kallabs.by
    - lst.kallabs.by
    - rp.kallabs.by
  # Access token lifetime in minutes
  access_lifetime: 1440
  # Refresh token lifetime in minutes
  refresh_lifetime: 1440 # 1 day